# Configuración de Upptime

sites:
  - name: UTM - OHELIT 
    url: https://remote2.ohelit.co/

status-website: false # No se generará una página externa

# Opcional: Si deseas agregar más servicios en el futuro, descomenta y ajusta:
# - name: Otro servicio
#   url: https://otro-servicio.com

# Elimina líneas comentadas innecesarias para evitar conflictos.
