# Change these first
owner: infraohelit # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OH - IP_PUBLIC
    url: https://186.155.9.52
  #- name: OH - Website
  #  url: https://www.ohelit.co/
  #- name: UTM - OHELIT 
  #  url: https://remote2.ohelit.co/
  #- name: OHVM SERVER - PUBLIC
  #  url: https://servicedesk.ohelit.co
  #- name: OHVM -  Administrativos
  #  url: https://unimonserrate-library-intra.ohelit.co/
  
  #  __dangerous__insecure: true
  #- name: Aulas virtuales
  #  url: https://aulasvirtuales.unimonserrate.edu.co/
  #  __dangerous__insecure: true
  #- name: Uvirtual
  #  url: https://uvirtual.unimonserrate.edu.co/
  #  __dangerous__insecure: true


assignees:
  - infraohelit

##status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  ##theme: ocean
  ##cname: estado.unimonserrate.edu.co
  # baseUrl: /your-repo-name
  ##logoUrl: https://www.unimonserrate.edu.co/wp-content/uploads/2021/08/logo_png-2.png
  ##name: Status IT services Unimon
  ##introTitle: "Estado de servicios de TI Unimonserrate"
  ##introMessage: En este sitio encuentras la información de estado actual de todos nuestros servicios WEB públicos
  ##navbar:
  ##  - title: Status
  ##    href: /
  ##  - title: GitHub
  ##    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
