# Configuración de Upptime
# Propietario del repositorio
owner: infraohelit
repo: status
repository: infraohelit/status

# Sitios a monitorear
sites:
  - name: OH-UTM
    url: https://remote2.ohelit.co/

  - name: OH-DOCKER-PUBLIC
    url: https://servicedesk.ohelit.co/

  - name: OH-NAS
    url: https://files.ohelit.co/

# Deshabilita la página de estado en GitHub Pages
status-website: false

