owner: infraohelit
repo: status
status-website: false # Esto evita generar una página externa
timezone: America/Bogota

# Definir el servicio a monitorear
checks:
  - name: UTM - OHELIT
    url: https://remote2.ohelit.co
