#blank_issues_enabled: true
#contact_links:
#  - name: Feature requests and ideas
#    url: https://github.com/upptime/upptime/discussions/new?category=ideas
#    about: Suggest an idea for this project
#  - name: Questions
#    url: https://github.com/upptime/upptime/discussions/new?category=q-a
#    about: Please ask and answer questions here
owner: infraohelit
repo: status
status-website: "https://infraohelit.github.io/status"
timezone: America/Bogota
checks:
  - name: UTM - OHELIT
    url: https://remote2.ohelit.co/
  - name: OHVM-SERVER-PUBLIC
    url: https://ohvm-server-public.ohelit.co/
