owner: infraohelit
repo: status
status-website: false # Esto evita generar una página externa
timezone: America/Bogota

# Definir el servicio a monitorear
checks:
  - name: oh-utm
    url: https://remote2.ohelit.co
# Definir el servicio a monitorear
checks:
  - name: oh-docker-public
    url: http://servicedesk.ohelit.co
# Definir el servicio a monitorear
checks:
  - name: oh-nas
    url: https://files.ohelit.co
